export const MENU_ITEMS = [
  { label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
  { label: 'Case Management', path: '/cases', icon: 'FolderKanban' },
  { label: 'Victims', path: '/victims', icon: 'Users' },
  { label: 'Vehicles', path: '/vehicles', icon: 'Car' },
  { label: 'Hospitals', path: '/hospitals', icon: 'Building2' },
  { label: 'Police', path: '/police', icon: 'Shield' },
  { label: 'Court', path: '/court', icon: 'Gavel' },
  { label: 'Advocates', path: '/advocates', icon: 'Briefcase' },
  { label: 'Documents', path: '/documents', icon: 'FileText' },
  { label: 'Compensation', path: '/compensation', icon: 'Wallet' },
  { label: 'Reports', path: '/reports', icon: 'BarChart3' },
  { label: 'Users', path: '/users', icon: 'UserCog' },
  { label: 'Notifications', path: '/notifications', icon: 'Bell' },
  { label: 'Audit Logs', path: '/audit-logs', icon: 'History' },
  { label: 'Calendar', path: '/calendar', icon: 'Calendar' },
  { label: 'Settings', path: '/settings', icon: 'Settings' },
  { label: 'Profile', path: '/profile', icon: 'UserCircle' },
]
